# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        exclude: legacy/
        language_version: python3.7
  - repo: https://gitlab.com/PyCQA/flake8
    rev: ""
    hooks:
      - id: flake8
        exclude: >
            (?x)^(
                legacy/|
                backend/emails/contents.py|
                backend/alembic/env.py
            )$
        language_version: python3.7
    # tried to to all the precommit work here, didn't work.
    # Leaving it as something we might want to look into
  - repo: https://github.com/prettier/prettier
    rev: "" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        files: \.(js|ts)$
        exclude: backend/
