services:
  - docker

install:
  - docker-compose pull

before_script:
  - docker-compose build
  - docker-compose run --rm api pip install -r requirements.txt
  - docker-compose run --rm api pip install -r requirements.dev.txt
  - docker-compose run --rm api python init_db.py

script:
  - docker-compose run --rm -e DATABASE_NAME='dbtest' api pytest

deploy:
  provider: script
  script: "./build.sh"
  on:
    all_branches: true
