"""add story missing fields

Revision ID: 0ceda838b5c1
Revises: 9d313d6bdc2b
Create Date: 2020-05-26 21:46:22.972505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ceda838b5c1'
down_revision = '9d313d6bdc2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('current_location', sa.String(length=128), nullable=True))
    op.add_column('stories', sa.Column('sickness_start', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'sickness_start')
    op.drop_column('stories', 'current_location')
    # ### end Alembic commands ###
