"""fips column changed from int to String(128)

Revision ID: 1b650bab183d
Revises: 7da9257097d2
Create Date: 2020-08-04 21:28:15.826309

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "1b650bab183d"
down_revision = "7da9257097d2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "nyt",
        "fips",
        existing_type=mysql.INTEGER(display_width=11),
        type_=sa.String(length=128),
        existing_nullable=True,
    )
    op.alter_column(
        "stories",
        "state",
        existing_type=mysql.VARCHAR(length=64),
        type_=sa.String(length=128),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "stories",
        "state",
        existing_type=sa.String(length=128),
        type_=mysql.VARCHAR(length=64),
        existing_nullable=True,
    )
    op.alter_column(
        "nyt",
        "fips",
        existing_type=sa.String(length=128),
        type_=mysql.INTEGER(display_width=11),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
