"""add table for storing multiple stories

Revision ID: 2fa6e1a3b8df
Revises: 69b610fddc4b
Create Date: 2020-08-20 23:37:05.405665

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "2fa6e1a3b8df"
down_revision = "69b610fddc4b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "my_stories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("story_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["story_id"], ["stories.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_my_stories_id"), "my_stories", ["id"], unique=False
    )
    op.drop_column("stories", "my_story")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stories", sa.Column("my_story", mysql.TEXT(), nullable=True)
    )
    op.drop_index(op.f("ix_my_stories_id"), table_name="my_stories")
    op.drop_table("my_stories")
    # ### end Alembic commands ###
