"""create nyt models

Revision ID: 41e44448c0e4
Revises: a31bfe8eba6b
Create Date: 2020-07-21 20:19:22.617625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "41e44448c0e4"
down_revision = "a31bfe8eba6b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nyt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("county", sa.String(), nullable=True),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column("fips", sa.Integer(), nullable=True),
        sa.Column("cases", sa.Integer(), nullable=True),
        sa.Column("deaths", sa.Integer(), nullable=True),
        sa.Column("confirmed_cases", sa.Integer(), nullable=True),
        sa.Column("confirmed_deaths", sa.Integer(), nullable=True),
        sa.Column("probable_cases", sa.Integer(), nullable=True),
        sa.Column("probable_deaths", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_nyt_id"), "nyt", ["id"], unique=False)
    op.create_table(
        "nyt_ttl",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_nyt_ttl_id"), "nyt_ttl", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_nyt_ttl_id"), table_name="nyt_ttl")
    op.drop_table("nyt_ttl")
    op.drop_index(op.f("ix_nyt_id"), table_name="nyt")
    op.drop_table("nyt")
    # ### end Alembic commands ###
