"""add close contacts table

Revision ID: 46a7b588a7b6
Revises: 93833e7cdbd5
Create Date: 2020-06-25 18:00:56.655546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "46a7b588a7b6"
down_revision = "93833e7cdbd5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "close_contacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("story_id", sa.Integer(), nullable=True),
        sa.Column("email", sa.String(length=128), nullable=True),
        sa.Column("phone_number", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["story_id"], ["stories.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_close_contacts_id"), "close_contacts", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_close_contacts_id"), table_name="close_contacts")
    op.drop_table("close_contacts")
    # ### end Alembic commands ###
