"""add latest my story column in story table

Revision ID: 475b8d61ec3a
Revises: 2fa6e1a3b8df
Create Date: 2020-09-07 23:26:21.861439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "475b8d61ec3a"
down_revision = "2fa6e1a3b8df"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stories", sa.Column("latest_my_story", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stories", "latest_my_story")
    # ### end Alembic commands ###
