"""Add db for trending words

Revision ID: 4b97d64fa93d
Revises: 4e16c97d06e7
Create Date: 2021-03-08 06:17:07.485897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4b97d64fa93d"
down_revision = "4e16c97d06e7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trending_words",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_trending_words_id"), "trending_words", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trending_words_id"), table_name="trending_words")
    op.drop_table("trending_words")
    # ### end Alembic commands ###
