"""Add table for comment spam

Revision ID: 73c1a03321bd
Revises: 4e16c97d06e7
Create Date: 2021-02-15 23:56:57.590999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "73c1a03321bd"
down_revision = "4e16c97d06e7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comment_spams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("spam", sa.Boolean(), nullable=True),
        sa.Column("comment_id", sa.Integer(), nullable=True),
        sa.Column("story_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["comment_id"], ["comments.id"],),
        sa.ForeignKeyConstraint(["story_id"], ["stories.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_comment_spams_id"), "comment_spams", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_comment_spams_id"), table_name="comment_spams")
    op.drop_table("comment_spams")
    # ### end Alembic commands ###
