"""add comment model

Revision ID: 78b6d95e9727
Revises: edace0efb31c
Create Date: 2021-01-16 10:31:42.706758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "78b6d95e9727"
down_revision = "edace0efb31c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("parent", sa.Integer(), nullable=True),
        sa.Column("story_id", sa.Integer(), nullable=True),
        sa.Column("my_story_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["my_story_id"], ["my_stories.id"],),
        sa.ForeignKeyConstraint(["parent"], ["comments.id"],),
        sa.ForeignKeyConstraint(["story_id"], ["stories.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_comments_id"), "comments", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_comments_id"), table_name="comments")
    op.drop_table("comments")
    # ### end Alembic commands ###
