"""Add created_at and updated_at columns to all models

Revision ID: 7d4ae3aca2ec
Revises: fca850040ebf
Create Date: 2020-05-29 20:30:04.625149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7d4ae3aca2ec"
down_revision = "fca850040ebf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stories", sa.Column("created_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "stories", sa.Column("updated_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "users", sa.Column("created_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "users", sa.Column("updated_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "updated_at")
    op.drop_column("users", "created_at")
    op.drop_column("stories", "updated_at")
    op.drop_column("stories", "created_at")
    # ### end Alembic commands ###
