"""add nyt county model

Revision ID: 7da9257097d2
Revises: 91a50206245d
Create Date: 2020-07-23 23:00:56.371160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7da9257097d2"
down_revision = "91a50206245d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nyt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("county", sa.String(length=128), nullable=True),
        sa.Column("state", sa.String(length=128), nullable=True),
        sa.Column("fips", sa.Integer(), nullable=True),
        sa.Column("cases", sa.Integer(), nullable=True),
        sa.Column("deaths", sa.Integer(), nullable=True),
        sa.Column("confirmed_cases", sa.Integer(), nullable=True),
        sa.Column("confirmed_deaths", sa.Integer(), nullable=True),
        sa.Column("probable_cases", sa.Integer(), nullable=True),
        sa.Column("probable_deaths", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_nyt_id"), "nyt", ["id"], unique=False)
    op.create_table(
        "nyt_ttl",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.Column("time_to_live", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_nyt_ttl_id"), "nyt_ttl", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_nyt_ttl_id"), table_name="nyt_ttl")
    op.drop_table("nyt_ttl")
    op.drop_index(op.f("ix_nyt_id"), table_name="nyt")
    op.drop_table("nyt")
    # ### end Alembic commands ###
