"""add timestamp column to NYT data

Revision ID: 80b579682838
Revises: e79af7945498
Create Date: 2020-08-06 18:27:26.792088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "80b579682838"
down_revision = "e79af7945498"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("nyt", sa.Column("timestamp", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nyt", "timestamp")
    # ### end Alembic commands ###
