"""add latitude and longtitude

Revision ID: 91a50206245d
Revises: 2551e1a3cb06
Create Date: 2020-07-21 18:33:49.658128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "91a50206245d"
down_revision = "2551e1a3cb06"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stories",
        sa.Column(
            "latitude", sa.Numeric(precision=10, scale=7), nullable=True
        ),
    )
    op.add_column(
        "stories",
        sa.Column(
            "longitude", sa.Numeric(precision=10, scale=7), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stories", "longitude")
    op.drop_column("stories", "latitude")
    # ### end Alembic commands ###
