"""add sickness end story field

Revision ID: 9ce127013b4f
Revises: 0ceda838b5c1
Create Date: 2020-05-27 18:18:24.592685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ce127013b4f'
down_revision = '0ceda838b5c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('sickness_end', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'sickness_end')
    # ### end Alembic commands ###
