"""add user story relationship

Revision ID: 9d313d6bdc2b
Revises: d128f1979d50
Create Date: 2020-05-26 16:20:43.047983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d313d6bdc2b'
down_revision = 'd128f1979d50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('story_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'stories', ['story_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'story_id')
    # ### end Alembic commands ###
