"""changed fips column type from int to string

Revision ID: a34c345b5721
Revises: 7da9257097d2
Create Date: 2020-08-04 21:07:48.627519

"""


# revision identifiers, used by Alembic.
revision = "a34c345b5721"
down_revision = "7da9257097d2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
