"""add latiude and longitude to stories

Revision ID: cd7d44990e4f
Revises: e96755d19f0c
Create Date: 2020-07-18 06:03:39.940032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cd7d44990e4f"
down_revision = "e96755d19f0c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stories",
        sa.Column(
            "latitude", sa.Numeric(precision=10, scale=7), nullable=True
        ),
    )
    op.add_column(
        "stories",
        sa.Column(
            "longitude", sa.Numeric(precision=10, scale=7), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stories", "longitude")
    op.drop_column("stories", "latitude")
    # ### end Alembic commands ###
