"""add story basic tables

Revision ID: d128f1979d50
Revises: d44a5a5a1fd2
Create Date: 2020-05-22 16:28:38.915164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd128f1979d50'
down_revision = 'd44a5a5a1fd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=64), nullable=True),
    sa.Column('ethnicity', sa.String(length=128), nullable=True),
    sa.Column('country_of_origin', sa.String(length=128), nullable=True),
    sa.Column('profession', sa.String(length=128), nullable=True),
    sa.Column('sick', sa.String(length=64), nullable=True),
    sa.Column('tested', sa.String(length=64), nullable=True),
    sa.Column('_medical_problems', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_id'), 'stories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stories_id'), table_name='stories')
    op.drop_table('stories')
    # ### end Alembic commands ###
