"""Add a commit hash column to nyt county data

Revision ID: d8868b76d30f
Revises: 80b579682838
Create Date: 2020-08-06 22:32:54.938612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d8868b76d30f"
down_revision = "80b579682838"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "nyt", sa.Column("commit", sa.String(length=128), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nyt", "commit")
    # ### end Alembic commands ###
