"""add table for like and dislike

Revision ID: edace0efb31c
Revises: 527194b9fb18
Create Date: 2020-10-14 02:51:38.265440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "edace0efb31c"
down_revision = "527194b9fb18"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "likes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("like", sa.Boolean(), nullable=True),
        sa.Column("my_story_id", sa.Integer(), nullable=True),
        sa.Column("liker_story_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["liker_story_id"], ["stories.id"],),
        sa.ForeignKeyConstraint(["my_story_id"], ["my_stories.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_likes_id"), "likes", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_likes_id"), table_name="likes")
    op.drop_table("likes")
    # ### end Alembic commands ###
